server:
    servlet:
        context-path: /
    port: 3691
spring:
    application:
        name: microservices-food-ordering-cloud-gateway-api-project
    cloud:
        config:
            fail-fast: false
            retry:
                initial-interval: 1000
                max-interval: 2000
                multiplier: 1.5
        gateway:
            routes:
            -   id: /microservices-food-ordering-restaurant-service-project
                predicates:
                - Path=/api/restaurant/**
                uri: lb://microservices-food-ordering-restaurant-service-project
            -   id: microservices-food-ordering-payment-service-project
                predicates:
                - Path=/api/payment/**
                uri: lb://microservices-food-ordering-payment-service-project
            -   id: microservices-food-ordering-order-service-projects
                predicates:
                - Path=/api/orders/**
                uri: lb://microservices-food-ordering-order-service-projects
            -   id: microservices-food-ordering-inventory-service-projects
                predicates:
                - Path=/api/inventory/**
                uri: lb://microservices-food-ordering-inventory-service-projects
    config:
        import: optional:configserver:http://localhost:9966
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:1030/realms/microservices_master_realm/protocol/openid-connect/certs
management:
    tracing:
        sampling:
            probability: 1.0                    