server:
    port: 8247
spring:
    application:
      name: microservices-food-ordering-payment-service-project
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://mysql_database:3306/microservicesdockerk8sfoodordering
      username: Kirti
      password: Kirti@02021997    
    jpa:
      hibernate:
        ddl-auto: update    
    cloud:
      config:
        fail-fast: false
        retry:
          initial-interval: 1000
          max-interval: 2000
          multiplier: 1.5
    config:      import:      - optional:configserver:http://localhost:9966
management:
    tracing:
        sampling:
            probability: 1.0      