server:
    port: 8243
spring:
    application:
        name: microservices-food-ordering-inventory-service-projects
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Kirti@02021997
        url: jdbc:mysql//mysql_database:3306/microservicesdockerk8sfoodordering
        username: Kirti
    jpa:
        hibernate:
            ddl-auto: update    
    cloud:
        config:
            fail-fast: false
            retry:
                initial-interval: 1000
                max-interval: 2000
                multiplier: 1.5
    config:
      import:
      - optional:configserver:http://localhost:9966
management:
    tracing:
        sampling:
            probability: 1.0      