apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  labels:
    name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: microservices-food-ordering-order-service
          image: kirtishekharpandey/microservices-food-ordering-order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8245
          resources:
          limits:
            memory: "700m"
            cpu: "700m"
      env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: order-service-application-name-configmap
              key: ORDER_SERVICE_APPLICATION_NAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: spring-profile-active-configmap
              key: SPRING_PROFILE_ACTIVE
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: eureka-service-registry-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        - name: SPRING_CONFIG_IMPORT
          valueFrom:
            configMapKeyRef:
              name: config-import-map
              key: SPRING_CONFIG_IMPORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: HOSTNAME
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: zipkin-tracing-endpoint-configmap
              key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT

---
apiVersion: v1
kind: Service
metadata:
  name: order-service-service
spec:
  selector:
    app: order-service-application
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 428
      targetPort: 8245
